services:
    nginx:
        image: nginx
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    node:
        build:
            dockerfile: docker/node/Dockerfile
            context: ./
        volumes:
            - ./app:/usr/src/app
        environment:
            - CHOKIDAR_USEPOLLING=true # Permet au watcher de fonctionner sous windows
        tty: true
